export enum PerfilUsuario {
  ADMIN = 'ADMIN',
  FUNCIONARIO = 'FUNCIONARIO',
  CLIENTE = 'CLIENTE'
}

export enum StatusReserva {
  AGUARDANDO_SINAL = 'AGUARDANDO_SINAL',
  CONFIRMADA = 'CONFIRMADA',
  QUITADA = 'QUITADA',
  CANCELADA = 'CANCELADA',
  FINALIZADA = 'FINALIZADA'
}

export enum TipoPagamento {
  SINAL = 'SINAL',
  QUITACAO = 'QUITACAO',
  TOTAL = 'TOTAL'
}
